version: '3.7'
services:
  app:
    image: text-search-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db

  # The DataBase
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_DB=posts
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "7777:5432"
#    volumes:
#      - posts_postgres:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:8.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - xpack.security.enabled=False
      - discovery.type=single-node
#      - ES_JAVA_OPTS="-Xms750m -Xmx750m"
    deploy:
      resources:
        limits:
          memory: 4G

#volumes:
#  posts_postgres:
