components:
  schemas:
    ListPost:
      properties:
        posts:
          items:
            $ref: '#/components/schemas/Post'
          type: array
        total_posts:
          example: 3
          type: integer
      type: object
    MatchPhrase:
      properties:
        match_phrase:
          example: "\u043A\u043E\u043D\u043A\u0443\u0440\u0441"
          type: string
      required:
      - match_phrase
      type: object
    Post:
      properties:
        created_date:
          example: '2019-12-29 20:14:28'
          format: date-time
          type: string
        id:
          example: 11
          type: integer
        rubrics:
          example:
          - VK-1603736028819866
          - VK-49725783613
          - VK-92549753485
          items:
            type: string
          type: array
        text:
          example: "\u041A\u043E\u043D\u043A\u0443\u0440\u0441 \u043D\u0430 \u041D\
            \u041E\u0412\u042B\u0419 \u0421\u041A\u0418\u041D \u203C"
          type: string
      type: object
    Response:
      properties:
        message:
          example: "\u0414\u0430\u043D\u043D\u044B\u0435 \u0432\u0432\u0435\u0434\u0435\
            \u043D\u044B \u043D\u0435\u0432\u0435\u0440\u043D\u043E"
          type: string
      type: object
info:
  title: TextSearchAPI
  version: v1
openapi: 3.0.3
paths:
  /static/{filename}: {}
  /api/search/:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchPhrase'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPost'
          description: "\u0420\u0435\u0437\u0443\u043B\u044C\u0442\u0430\u0442\u044B\
            \ \u043F\u043E\u0438\u0441\u043A\u0430"
        '400':
          content:
            application/json:
              example:
                message: "\u0414\u0430\u043D\u043D\u044B\u0435 \u0432\u0432\u0435\u0434\
                  \u0435\u043D\u044B \u043D\u0435\u0432\u0435\u0440\u043D\u043E"
              schema:
                $ref: '#/components/schemas/Response'
          description: "\u0414\u0430\u043D\u043D\u044B\u0435 \u0432\u0432\u0435\u0434\
            \u0435\u043D\u044B \u043D\u0435\u0432\u0435\u0440\u043D\u043E"
      summary: "\u041F\u043E\u0438\u0441\u043A \u043F\u043E\u0441\u0442\u043E\u0432\
        \ \u043F\u043E \u0441\u043E\u0434\u0435\u0440\u0436\u0430\u043D\u0438\u044E\
        \ \u0432 \u043D\u0438\u0445 \u043E\u043F\u0440\u0435\u0434\u0435\u043B\u0451\
        \u043D\u043D\u043E\u0433\u043E \u0442\u0435\u043A\u0441\u0442\u0430, \u0432\
        \u043E\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 \u043F\u043E\u0441\u043B\
        \u0435\u0434\u043D\u0438\u0435 20 \u043F\u043E\u0441\u0442\u043E\u0432 \u0438\
        \u043B\u0438 \u043C\u0435\u043D\u044C\u0448\u0435"
      tags:
      - TextSearch
  /api/delete/{post_id}/:
    delete:
      parameters:
      - example: 2
        in: path
        name: post_id
        required: true
        schema:
          description: post_id to delete
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                message: "\u041A\u043E\u0434 \u0443\u0441\u043F\u0435\u0448\u043D\u043E\
                  \ \u0443\u0434\u0430\u043B\u0451\u043D"
              schema:
                $ref: '#/components/schemas/Response'
          description: "\u041F\u043E\u0441\u0442 \u0443\u0441\u043F\u0435\u0448\u043D\
            \u043E \u0443\u0434\u0430\u043B\u0451\u043D"
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: "\u0414\u0430\u043D\u043D\u044B\u0435 \u0432\u0432\u0435\u0434\
            \u0435\u043D\u044B \u043D\u0435\u0432\u0435\u0440\u043D\u043E"
        '409':
          content:
            application/json:
              example:
                message: "\u041E\u0448\u0438\u0431\u043A\u0430 \u0443\u0434\u0430\u043B\
                  \u0435\u043D\u0438\u044F"
              schema:
                $ref: '#/components/schemas/Response'
          description: "\u041E\u0448\u0438\u0431\u043A\u0430 \u0443\u0434\u0430\u043B\
            \u0435\u043D\u0438\u044F"
      summary: "\u0423\u0434\u0430\u043B\u0438\u0442\u044C \u043A\u043E\u0434"
      tags:
      - TextSearch
  /api/swagger/: {}
  /api/docs/dist/{filename}: {}
  /api/docs/{path}: {}
servers:
- description: develop
  url: http://localhost:5001

